#!/usr/bin/env python3
"""
test_algebra.py — mechanized verification of the Owl Semaphore's algebraic claims.

Pure Python standard library; runs under `make test` (unittest discover).

AGENTS.md asserts two mathematical results as "verified by brute-force
enumeration" and instructs future contributors never to reproduce the second
one's inverse. Both were verified off-repo in prose. This module commits the
enumeration itself, so the claims are enforced by CI rather than remembered:

  1. V4 IS FORCED (AGENTS.md "What this project is"). Two independent commuting
     involutions -- orientation-of-stance (sigma_v) and locus-of-audit (sigma_h)
     -- generate exactly four elements; closure forces C2 = sigma_v . sigma_h;
     every element is its own inverse, which selects V4 over C4 (the only other
     group of order 4) and over any non-abelian group.

  2. "V4 IS THE AUTOMORPHISM GROUP OF DM4" IS FALSE (AGENTS.md "A specific math
     error to never reproduce"). Enumerated over all 24 permutations of the four
     De Morgan values, Aut(DM4) as a De Morgan algebra (preserving meet, join,
     and negation) is isomorphic to Z2 -- identity and conflation only. De Morgan
     negation is an order-REVERSING anti-automorphism, not an automorphism. The
     V4 that genuinely appears is the group generated by the two negations acting
     on the four values: a symmetry group of the set, not Aut(DM4).

Claim 2 is a NEGATIVE test. It fails if someone "corrects" the repo toward the
false statement -- which is precisely the drift AGENTS.md warns against.
"""
import itertools
import unittest

# --- The four states, realized as the symmetry group of a rectangle -----------
# Each element is a 2x2 integer matrix acting on (stance, locus).
I = ((1, 0), (0, 1))            # NORMATIVE      -- identity
SV = ((-1, 0), (0, 1))          # NON-NORMATIVE  -- orientation-of-stance
SH = ((1, 0), (0, -1))          # METACOGNITIVE  -- locus-of-audit
C2 = ((-1, 0), (0, -1))         # CRITICAL       -- 180 deg rotation

ELEMENTS = {"I": I, "sigma_v": SV, "sigma_h": SH, "C2": C2}
STATE_OF = {"I": "NORMATIVE", "sigma_v": "NON-NORMATIVE",
            "sigma_h": "METACOGNITIVE", "C2": "CRITICAL"}


def mul(a, b):
    """2x2 matrix product."""
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(2))
                       for j in range(2)) for i in range(2))


def det(m):
    return m[0][0] * m[1][1] - m[0][1] * m[1][0]


def name_of(m):
    for n, e in ELEMENTS.items():
        if e == m:
            return n
    return None


class TestV4IsForced(unittest.TestCase):
    """The algebra claims of OWL-SEMAPHORE-SYSTEM.md section 2.3 / 4A."""

    def test_closure(self):
        """Every product of two elements is again one of the four elements."""
        for a, b in itertools.product(ELEMENTS, repeat=2):
            self.assertIsNotNone(
                name_of(mul(ELEMENTS[a], ELEMENTS[b])),
                f"{a} . {b} escaped the set -- closure violated")

    def test_every_element_is_an_involution(self):
        """x . x = I for all x. This is what selects V4 over C4."""
        for n, e in ELEMENTS.items():
            self.assertEqual(mul(e, e), I, f"{n} is not its own inverse")

    def test_no_element_has_order_four(self):
        """C4 requires a generator of order 4; V4 has none. Explicit exclusion."""
        for n, e in ELEMENTS.items():
            order = 1
            acc = e
            while acc != I and order < 8:
                acc = mul(acc, e)
                order += 1
            self.assertIn(order, (1, 2),
                          f"{n} has order {order}; an order-4 element would make this C4")

    def test_abelian(self):
        """The two generating involutions commute, so the group is abelian."""
        for a, b in itertools.product(ELEMENTS, repeat=2):
            self.assertEqual(
                mul(ELEMENTS[a], ELEMENTS[b]), mul(ELEMENTS[b], ELEMENTS[a]),
                f"{a} and {b} do not commute")

    def test_critical_is_the_composition(self):
        """CRITICAL = C2 = sigma_v . sigma_h -- closure forces the fourth element.

        Guards the v3.0.1 section 4A.1 locus-axis errata: CRITICAL sits at the
        composition of BOTH reflections, not at the object level.
        """
        self.assertEqual(mul(SV, SH), C2)
        self.assertEqual(mul(SH, SV), C2)

    def test_generators_are_independent(self):
        """Neither generator is a power of the other; together they span the group."""
        self.assertNotEqual(SV, SH)
        generated = {I}
        frontier = [SV, SH]
        for g in frontier:
            generated |= {mul(x, g) for x in generated} | {g}
        for _ in range(3):
            generated |= {mul(a, b) for a in generated for b in generated}
        self.assertEqual(len(generated), 4,
                         "the two involutions must generate exactly four elements")
        self.assertEqual({name_of(m) for m in generated}, set(ELEMENTS))

    def test_determinant_matches_published_table(self):
        """Determinants match the README's four-state table (+1/-1 per state)."""
        expected = {"NORMATIVE": 1, "NON-NORMATIVE": -1,
                    "CRITICAL": 1, "METACOGNITIVE": -1}
        for n, e in ELEMENTS.items():
            self.assertEqual(det(e), expected[STATE_OF[n]],
                             f"determinant of {STATE_OF[n]} disagrees with the spec table")

    def test_isomorphic_to_klein_four_group(self):
        """Structural identification: abelian, order 4, exponent 2 => V4."""
        squares = {mul(e, e) for e in ELEMENTS.values()}
        self.assertEqual(len(ELEMENTS), 4)
        self.assertEqual(squares, {I}, "exponent must be 2 for V4")


# --- DM4: the De Morgan diamond ----------------------------------------------
# Values: F(alse) < N(either), B(oth) < T(rue); N and B are incomparable.
F, N, T, B = "F", "N", "T", "B"
VALUES = [F, N, T, B]
LEQ = {(F, F), (F, N), (F, B), (F, T),
       (N, N), (N, T),
       (B, B), (B, T),
       (T, T)}
NEG = {F: T, T: F, N: N, B: B}       # De Morgan negation
CONFLATION = {F: F, T: T, N: B, B: N}  # knowledge-negation


def meet(x, y):
    lows = [z for z in VALUES if (z, x) in LEQ and (z, y) in LEQ]
    return next(z for z in lows if all((w, z) in LEQ for w in lows))


def join(x, y):
    highs = [z for z in VALUES if (x, z) in LEQ and (y, z) in LEQ]
    return next(z for z in highs if all((z, w) in LEQ for w in highs))


class TestDeMorganAutomorphismClaim(unittest.TestCase):
    """AGENTS.md: 'V4 is the automorphism group of DM4' is FALSE.

    NEGATIVE TESTS -- these fail if the repo drifts toward the false claim.
    """

    def _automorphisms(self):
        found = []
        for perm in itertools.permutations(VALUES):
            s = dict(zip(VALUES, perm))
            if all(s[meet(x, y)] == meet(s[x], s[y]) and
                   s[join(x, y)] == join(s[x], s[y])
                   for x in VALUES for y in VALUES) and \
               all(s[NEG[x]] == NEG[s[x]] for x in VALUES):
                found.append(s)
        return found

    def test_lattice_is_well_formed(self):
        """Sanity: DM4 really is the diamond -- N and B incomparable, F bottom, T top."""
        self.assertNotIn((N, B), LEQ)
        self.assertNotIn((B, N), LEQ)
        self.assertEqual(meet(N, B), F)
        self.assertEqual(join(N, B), T)

    def test_aut_dm4_has_order_two_not_four(self):
        """Brute force over all 24 permutations: |Aut(DM4)| == 2, so it is Z2."""
        auts = self._automorphisms()
        self.assertEqual(
            len(auts), 2,
            "Aut(DM4) as a De Morgan algebra must have order 2 (Z2); "
            "order 4 would be the false V4 claim AGENTS.md forbids")

    def test_aut_dm4_is_exactly_identity_and_conflation(self):
        auts = self._automorphisms()
        identity = {v: v for v in VALUES}
        self.assertIn(identity, auts)
        self.assertIn(CONFLATION, auts)

    def test_de_morgan_negation_is_not_an_automorphism(self):
        """NEG is order-reversing -- an anti-automorphism, not an automorphism."""
        self.assertNotIn(NEG, self._automorphisms())
        self.assertTrue(all((NEG[y], NEG[x]) in LEQ for (x, y) in LEQ),
                        "De Morgan negation must reverse the lattice order")

    def test_the_real_v4_is_generated_by_the_two_negations(self):
        """The genuine V4 acts on the SET of four values, and is not Aut(DM4)."""
        composite = {v: CONFLATION[NEG[v]] for v in VALUES}
        group = [{v: v for v in VALUES}, NEG, CONFLATION, composite]
        frozen = {tuple(sorted(g.items())) for g in group}
        self.assertEqual(len(frozen), 4, "the two negations must generate four maps")
        for g in group:
            self.assertTrue(all(g[g[v]] == v for v in VALUES),
                            "every generated element must be an involution")


class TestStructuralRhymeIsNotEquivalence(unittest.TestCase):
    """AGENTS.md: sharing V4 is a structural rhyme, not kinship with Belnap-Dunn.

    The Owl Semaphore's V4 acts on stance-operations; DM4's V4 acts on
    truth-values. Same group, different domain -- and the Owl Semaphore carries
    no lattice structure at all, which is the formal content of 'not a logic'.
    """

    def test_owl_states_carry_no_lattice_order(self):
        """There is no meet/join on the four states -- they are operations."""
        self.assertFalse(hasattr(ELEMENTS["I"], "meet"))
        # Group elements compose; they are not ordered by entailment.
        self.assertEqual(mul(SV, SV), I,
                         "composition, not conjunction, is the state operation")

    def test_both_structures_are_order_four_but_act_on_different_carriers(self):
        self.assertEqual(len(ELEMENTS), 4)
        self.assertEqual(len(VALUES), 4)
        self.assertNotEqual(set(ELEMENTS.values()), set(VALUES))


if __name__ == "__main__":
    unittest.main(verbosity=2)
