"""Release bundle completeness test (v2.0.2+).

The canonical GitHub release bundle (`owl-semaphore-<TAG>.zip`) is assembled
by `.github/workflows/release-assets.yml` from the list of paths in
`RELEASE-BUNDLE-MANIFEST.txt` at the repo root. The manifest is the single
source of truth for what must appear inside that bundle.

This test enforces two invariants in CI:

  1. Every non-comment entry in `RELEASE-BUNDLE-MANIFEST.txt` exists at
     the repo root (file entries are files; entries ending in `/` are
     directories). This catches the v2.0.2-era regression where the
     workflow's hand-maintained `cp` list dropped
     `OWL-SEMAPHORE-EXPLANATION.pdf` from the bundle.
  2. The manifest covers every canonical release-facing artifact the
     project documents as part of a release — the six specification PDFs,
     their markdown sources, the citation / Zenodo / license / hash /
     integrity files, README, CHANGELOG, and the assets tree. This catches
     the inverse regression: a new canonical artifact being added to the
     repo without being added to the bundle manifest.

The test does not run the workflow itself; it validates the manifest the
workflow consumes, which is the durable failure surface.
"""

from __future__ import annotations

import os
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST_PATH = os.path.join(REPO, "RELEASE-BUNDLE-MANIFEST.txt")

# The set of paths the project documents as canonical release artifacts.
# RELEASE-BUNDLE-MANIFEST.txt must list every one of these. New canonical
# artifacts should be added BOTH here and to the manifest in the same PR.
REQUIRED_FILES = (
    # License + provenance
    "LICENSE",
    "INTEGRITY-MANIFEST.md",
    "RELEASE-HASHES.txt",
    "VALIDATION-SCRIPT-SPEC.md",
    # Citation + Zenodo metadata
    "CITATION.cff",
    ".zenodo.json",
    # Human-readable project docs
    "README.md",
    "CHANGELOG.md",
    # Canonical specification source (markdown)
    "OWL-SEMAPHORE-SYSTEM.md",
    "OWL-SEMAPHORE-EXPLANATION.md",
    "OWL-1-NORMATIVE.md",
    "OWL-2-NON-NORMATIVE.md",
    "OWL-3-CRITICAL.md",
    "OWL-4-METACOGNITIVE.md",
    # Canonical specification PDFs
    "OWL-SEMAPHORE-SYSTEM.pdf",
    "OWL-SEMAPHORE-EXPLANATION.pdf",
    "OWL-1-NORMATIVE.pdf",
    "OWL-2-NON-NORMATIVE.pdf",
    "OWL-3-CRITICAL.pdf",
    "OWL-4-METACOGNITIVE.pdf",
)

REQUIRED_DIRS = (
    "assets",
)


def _parse_manifest() -> tuple[list[str], list[str]]:
    """Return (files, directories) listed in RELEASE-BUNDLE-MANIFEST.txt."""
    files: list[str] = []
    dirs: list[str] = []
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            if line.endswith("/"):
                dirs.append(line.rstrip("/"))
            else:
                files.append(line)
    return files, dirs


class ReleaseBundleManifestTest(unittest.TestCase):
    """Verify the release bundle manifest is complete and resolvable."""

    def test_manifest_exists(self) -> None:
        self.assertTrue(
            os.path.isfile(MANIFEST_PATH),
            "RELEASE-BUNDLE-MANIFEST.txt must exist at the repository root",
        )

    def test_every_manifest_file_entry_exists_on_disk(self) -> None:
        files, _ = _parse_manifest()
        missing = [
            entry for entry in files
            if not os.path.isfile(os.path.join(REPO, entry))
        ]
        # PDFs are generated by `make pdfs`; in a clean checkout they may
        # not be present. Tolerate missing PDF entries here (the workflow
        # validates them at tag time, when PDFs are part of the tagged
        # commit) but never tolerate missing non-PDF entries.
        non_pdf_missing = [m for m in missing if not m.lower().endswith(".pdf")]
        self.assertEqual(
            non_pdf_missing,
            [],
            "RELEASE-BUNDLE-MANIFEST.txt references missing files: "
            + ", ".join(non_pdf_missing),
        )

    def test_every_manifest_dir_entry_exists_on_disk(self) -> None:
        _, dirs = _parse_manifest()
        missing = [
            entry for entry in dirs
            if not os.path.isdir(os.path.join(REPO, entry))
        ]
        self.assertEqual(
            missing,
            [],
            "RELEASE-BUNDLE-MANIFEST.txt references missing directories: "
            + ", ".join(missing),
        )

    def test_manifest_covers_every_required_file(self) -> None:
        files, _ = _parse_manifest()
        listed = set(files)
        omitted = [name for name in REQUIRED_FILES if name not in listed]
        self.assertEqual(
            omitted,
            [],
            "RELEASE-BUNDLE-MANIFEST.txt is missing canonical release files: "
            + ", ".join(omitted),
        )

    def test_manifest_covers_every_required_dir(self) -> None:
        _, dirs = _parse_manifest()
        listed = set(dirs)
        omitted = [name for name in REQUIRED_DIRS if name not in listed]
        self.assertEqual(
            omitted,
            [],
            "RELEASE-BUNDLE-MANIFEST.txt is missing canonical release dirs: "
            + ", ".join(omitted),
        )

    def test_workflow_reads_manifest(self) -> None:
        """The release workflow must consume the manifest, not a hand-written list."""
        workflow_path = os.path.join(
            REPO, ".github", "workflows", "release-assets.yml"
        )
        with open(workflow_path, "r", encoding="utf-8") as f:
            workflow = f.read()
        self.assertIn(
            "RELEASE-BUNDLE-MANIFEST.txt",
            workflow,
            "release-assets.yml must read RELEASE-BUNDLE-MANIFEST.txt to "
            "assemble the bundle (single source of truth)",
        )


if __name__ == "__main__":
    unittest.main()
