#!/usr/bin/env python3
"""Update the generated sections of INTEGRITY-MANIFEST.md (v3.0.1).

Reads RELEASE-HASHES.txt (produced by scripts/compute_hashes.py) and rewrites:

  1. the block between the markers ``<!-- BEGIN GENERATED HASHES -->`` and
     ``<!-- END GENERATED HASHES -->`` (appended at the end of the manifest
     if the markers are missing), and
  2. the ``sha3_512:`` field of every §11.1 per-file record whose ``path:``
     appears in RELEASE-HASHES.txt,

so that RELEASE-HASHES.txt is the single source of truth for every hash
value in the manifest.
"""

from __future__ import annotations

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HASHES = os.path.join(REPO, "RELEASE-HASHES.txt")
MANIFEST = os.path.join(REPO, "INTEGRITY-MANIFEST.md")

BEGIN = "<!-- BEGIN GENERATED HASHES -->"
END = "<!-- END GENERATED HASHES -->"

HEADER = """## Generated Hash Records (v3.0.1)

The block below is regenerated by `scripts/update_manifest.py` from
`RELEASE-HASHES.txt`. Do not hand-edit between the markers.
"""


def main() -> int:
    if not os.path.isfile(HASHES):
        print(f"ERROR: {HASHES} not found. Run scripts/compute_hashes.py first.", file=sys.stderr)
        return 1

    with open(HASHES, "r") as f:
        hash_lines = [ln.rstrip() for ln in f if ln.strip()]

    parsed = []
    for ln in hash_lines:
        m = re.match(r"SHA3-512\((.+)\)= ([0-9a-f]{128})$", ln)
        if not m:
            continue
        parsed.append((m.group(1), m.group(2)))

    block_lines = [BEGIN, "", HEADER, "```text"]
    for path, digest in parsed:
        block_lines.append(f"{path}: {digest}")
    block_lines += ["```", "", END]
    block = "\n".join(block_lines) + "\n"

    with open(MANIFEST, "r") as f:
        manifest_text = f.read()

    if BEGIN in manifest_text and END in manifest_text:
        new_manifest = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            block.strip(),
            manifest_text,
            flags=re.DOTALL,
        )
    else:
        if not manifest_text.endswith("\n"):
            manifest_text += "\n"
        new_manifest = manifest_text + "\n" + block

    # Rewrite the sha3_512 field of each per-file record (§11.1) from the
    # same hash source. Records use the canonical format from §10:
    #   - path: <path>
    #     ...
    #     sha3_512: <digest>
    updated_records = 0
    for path, digest in parsed:
        pattern = (
            r"(?m)(- path: "
            + re.escape(path)
            + r"\n(?:  \S[^\n]*\n)*?  sha3_512: )[0-9a-f]{128}"
        )
        new_manifest, n = re.subn(pattern, r"\g<1>" + digest, new_manifest)
        updated_records += n

    with open(MANIFEST, "w") as f:
        f.write(new_manifest)

    print(
        f"Wrote {MANIFEST} "
        f"({len(parsed)} generated-block entries, {updated_records} per-file records updated)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
