#!/usr/bin/env python3
"""Update the generated section of INTEGRITY-MANIFEST.md (v1.3.0-rc).

Reads RELEASE-HASHES.txt (produced by scripts/compute_hashes.py) and rewrites
the block between the markers ``<!-- BEGIN GENERATED HASHES -->`` and
``<!-- END GENERATED HASHES -->`` in INTEGRITY-MANIFEST.md so that the manifest
always reflects the current hash output. If the markers are missing, the block
is appended at the end of the manifest.
"""

from __future__ import annotations

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HASHES = os.path.join(REPO, "RELEASE-HASHES.txt")
MANIFEST = os.path.join(REPO, "INTEGRITY-MANIFEST.md")

BEGIN = "<!-- BEGIN GENERATED HASHES -->"
END = "<!-- END GENERATED HASHES -->"

HEADER = """## Generated Hash Records (v1.3.0-rc)

The block below is regenerated by `scripts/update_manifest.py` from
`RELEASE-HASHES.txt`. Do not hand-edit between the markers.
"""


def main() -> int:
    if not os.path.isfile(HASHES):
        print(f"ERROR: {HASHES} not found. Run scripts/compute_hashes.py first.", file=sys.stderr)
        return 1

    with open(HASHES, "r") as f:
        hash_lines = [ln.rstrip() for ln in f if ln.strip()]

    parsed = []
    for ln in hash_lines:
        m = re.match(r"SHA3-512\((.+)\)= ([0-9a-f]{128})$", ln)
        if not m:
            continue
        parsed.append((m.group(1), m.group(2)))

    block_lines = [BEGIN, "", HEADER, "```text"]
    for path, digest in parsed:
        block_lines.append(f"{path}: {digest}")
    block_lines += ["```", "", END]
    block = "\n".join(block_lines) + "\n"

    with open(MANIFEST, "r") as f:
        manifest_text = f.read()

    if BEGIN in manifest_text and END in manifest_text:
        new_manifest = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            block.strip(),
            manifest_text,
            flags=re.DOTALL,
        )
    else:
        if not manifest_text.endswith("\n"):
            manifest_text += "\n"
        new_manifest = manifest_text + "\n" + block

    with open(MANIFEST, "w") as f:
        f.write(new_manifest)

    print(f"Wrote {MANIFEST} (with {len(parsed)} hash entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
